### random库的应用

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:

# ============ 1. 随机整数 randint ============
a = np.random.randint(0, 10, (3, 4))
print("randint:\n", a)
# 生成3行4列，值在[0,10)之间的随机整数矩阵
# randint(low, high, size)
#   low:  最小值（包含）
#   high: 最大值（不包含）
#   size: 形状，可以是整数或元组

# ============ 2. 随机浮点数 random ============
b = np.random.random((3, 4))
print("random:\n", b)
# 生成3行4列，值在[0,1)之间的随机浮点数矩阵
# random(size)
#   size: 形状，可以是整数或元组
#   范围固定是[0,1)，不能自定义

# ============ 3. 正态分布 randn ============
c = np.random.randn(3, 4)
print("randn:\n", c)
# 生成3行4列，均值0、标准差1的正态分布随机数
# randn(d0, d1, ...)
#   d0,d1...: 直接传入每个维度的大小，注意不用元组
#   大部分值集中在-3~3之间，有正有负

# ============ 4. 均匀分布 uniform ============
d = np.random.uniform(5, 10, (3, 4))
print("uniform:\n", d)
# 生成3行4列，值在[5,10)之间均匀分布的浮点数
# uniform(low, high, size)
#   low:  最小值（包含），默认0
#   high: 最大值（不包含），默认1
#   size: 形状，可以是整数或元组

# ============ 5. 随机选取 choice ============
arr = [10, 20, 30, 40, 50]
e = np.random.choice(arr, size=(3, 4))
print("choice:\n", e)
# 从arr中随机抽取，生成3行4列的矩阵
# choice(a, size, replace, p)
#   a:       被抽取的数组或整数（整数n则从range(n)中抽）
#   size:    输出形状
#   replace: 是否可重复抽取，默认True
#   p:       每个元素被抽到的概率，默认均等

# ============ 6. 打乱顺序 shuffle ============
f = np.array([1, 2, 3, 4, 5])
np.random.shuffle(f)
print("shuffle:\n", f)
# 原数组被打乱顺序，注意shuffle直接修改原数组，无返回值
# shuffle(x)
#   x: 要打乱的数组，直接在原数组上修改

# ============ 7. 固定随机种子 seed ============
np.random.seed(42)
g = np.random.randint(0, 10, 5)
print("seed固定后:\n", g)
# 只要seed相同，每次运行结果都一样，方便复现实验结果
# seed(seed)
#   seed: 任意整数，相同的seed产生相同的随机序列


randint:
 [[9 2 6 7]
 [4 3 7 7]
 [2 5 4 1]]
random:
 [[7.21998772e-01 9.38552709e-01 7.78765841e-04 9.92211559e-01]
 [6.17481510e-01 6.11653160e-01 7.06630522e-03 2.30624250e-02]
 [5.24774660e-01 3.99860972e-01 4.66656632e-02 9.73755519e-01]]
randn:
 [[-0.25104397 -0.16386712 -1.47632969  1.48698096]
 [-0.02445518  0.35555132  0.41701111  0.83246186]
 [-0.29339915 -0.02983857  0.09512578  0.66465434]]
uniform:
 [[6.92708251 5.07983126 6.15446913 6.20512733]
 [8.41631759 8.04998329 9.16597456 5.86682327]
 [6.95530304 5.91118044 8.77680705 7.12577937]]
choice:
 [[20 40 50 20]
 [20 40 20 20]
 [40 40 10 50]]
shuffle:
 [4 1 3 2 5]
seed固定后:
 [6 3 7 4 6]
