## 索引切片

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
array1=np.arange(1,10)
print(array1[0],array1[array1.size-1])
print(array1[-array1.size],array1[-1])

1 9
1 9


In [10]:
array2=np.zeros((3,3),dtype='i8')
for i in range(3):
    for j in range(3):
        array2[i][j]=i+j+1
for _ in range(3):
    print(array2[_])

print(array2[0][0])
print(array2[-1][-1])
print(array2[-2][-2])
print(array2[-3,-2])
    

[1 2 3]
[2 3 4]
[3 4 5]
1
5
3
2


1.切片索引

In [18]:
#复习：从后往前切一片
a=list(range(1,11))
print(a)
print(a[-3::-1])
print(a[-2:-5:-1])
print(a[-2:0:-1])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[8, 7, 6, 5, 4, 3, 2, 1]
[9, 8, 7]
[9, 8, 7, 6, 5, 4, 3, 2]


In [26]:
array3=np.array([[1,2,3],[4,5,6],[7,8,9]])
#取一个元素
print(array3[2,2])
#取一行
print(array3[1,:])
print(array3[1])
#意思是取出第一行所有列

#取一列
print(array3[:,2])
#：意思是保留这个维度，所有行第二列

#取子矩阵
print(array3[0:3,1:3])
#取出第0行到第2行，第1列到第二列

#切片也可以加步长



9
[4 5 6]
[4 5 6]
[3 6 9]
[[2 3]
 [5 6]
 [8 9]]


2.索引切片降维问题

In [30]:
print(array3[0,:],array3[0,:].shape,array3[0,:].ndim)
print(array3[:,0],array3[:,0].shape,array3[:,0].ndim)

[1 2 3] (3,) 1
[1 4 7] (3,) 1


In [32]:
print(array3[0:1,:],array3[0:1,:].shape,array3[0:1,:].ndim)
print(array3[:,0:1],array3[:,0:1].shape,array3[:,0:1].ndim)

[[1 2 3]] (1, 3) 2
[[1]
 [4]
 [7]] (3, 1) 2


In [ ]:
#三维数组
# 创建示例三维数组，shape = (2, 3, 4)
# 轴0 = 块(depth), 轴1 = 行, 轴2 = 列
arr = np.arange(24).reshape(2, 3, 4)

print("=" * 50)
print("原始数组 arr.shape =", arr.shape)
print("=" * 50)
print(arr)
print()

# ── 1. 基础索引 ──────────────────────────────────
print("── 1. 基础索引 ──────────────────────────────")

# 取第0块、第1行、第2列 → 标量
print("arr[0, 1, 2] =", arr[0, 1, 2])          # 6

# 负索引：取最后一块、最后一行、最后一列
print("arr[-1, -1, -1] =", arr[-1, -1, -1])    # 23

# 只指定第一轴 → 取整块，shape (3, 4)
print("arr[1] shape:", arr[1].shape)
print(arr[1])

# 指定两个轴 → 取一行，shape (4,)
print("arr[0, 2] shape:", arr[0, 2].shape)
print(arr[0, 2])
print()

# ── 2. 单轴切片 ──────────────────────────────────
print("── 2. 单轴切片 ──────────────────────────────")

# 沿轴0切取第1块，shape (1, 3, 4)
print("arr[1:, :, :] shape:", arr[1:, :, :].shape)
print(arr[1:, :, :])

# 沿轴1切取前2行，shape (2, 2, 4)
print("arr[:, :2, :] shape:", arr[:, :2, :].shape)
print(arr[:, :2, :])

# 沿轴2切取第1~3列，shape (2, 3, 2)
print("arr[:, :, 1:3] shape:", arr[:, :, 1:3].shape)
print(arr[:, :, 1:3])

# 沿轴2切取最后两列，shape (2, 3, 2)
print("arr[:, :, -2:] shape:", arr[:, :, -2:].shape)
print(arr[:, :, -2:])
print()

# ── 3. 多轴切片 ──────────────────────────────────
print("── 3. 多轴切片 ──────────────────────────────")

# 所有块，后2行，前2列，shape (2, 2, 2)
print("arr[:, 1:, :2] shape:", arr[:, 1:, :2].shape)
print(arr[:, 1:, :2])

# 第1块，前1行，前3列，shape (1, 3)
print("arr[1, :1, :3] shape:", arr[1, :1, :3].shape)
print(arr[1, :1, :3])

# 两块，中间行，中间两列，shape (2, 1, 2)
print("arr[:, 1:2, 1:3] shape:", arr[:, 1:2, 1:3].shape)
print(arr[:, 1:2, 1:3])
print()

# ── 4. 步长切片 ──────────────────────────────────
print("── 4. 步长切片 ──────────────────────────────")

# 列方向每隔1列取，shape (2, 3, 2)
print("arr[:, :, ::2] shape:", arr[:, :, ::2].shape)
print(arr[:, :, ::2])

# 列方向反转，shape (2, 3, 4)
print("arr[:, :, ::-1] shape:", arr[:, :, ::-1].shape)
print(arr[:, :, ::-1])

# 所有轴反转
print("arr[::-1, ::-1, ::-1] 第一个元素:", arr[::-1, ::-1, ::-1].flat[0])  # 23

# 行方向每2行取1行，shape (2, 2, 4)
print("arr[:, ::2, :] shape:", arr[:, ::2, :].shape)
print(arr[:, ::2, :])
print()

# ── 5. 省略号 ... ────────────────────────────────
print("── 5. 省略号 ... ────────────────────────────")

# 取最后一列，等价于 arr[:, :, -1]，shape (2, 3)
print("arr[..., -1] shape:", arr[..., -1].shape)
print(arr[..., -1])

# 取第0块，等价于 arr[0, :, :]，shape (3, 4)
print("arr[0, ...] shape:", arr[0, ...].shape)
print(arr[0, ...])

# 取所有块的第0行，shape (2, 4)
print("arr[:, 0, ...] shape:", arr[:, 0, ...].shape)
print(arr[:, 0, ...])

# 取前两列，shape (2, 3, 2)
print("arr[..., :2] shape:", arr[..., :2].shape)
print(arr[..., :2])
print()

# ── 6. np.newaxis 插入新维度 ─────────────────────
print("── 6. np.newaxis 插入新维度 ─────────────────")

# 在轴0前插入新维度，shape (1, 2, 3, 4)
print("arr[np.newaxis].shape:", arr[np.newaxis].shape)

# 在轴1插入新维度，shape (2, 1, 3, 4)
print("arr[:, np.newaxis].shape:", arr[:, np.newaxis].shape)

# None 是 np.newaxis 的同义词
print("arr[0, None].shape:", arr[0, None].shape)     # (1, 3, 4)

# 在末尾插入新维度，shape (2, 3, 4, 1)
print("arr[..., np.newaxis].shape:", arr[..., np.newaxis].shape)
print()

# ── 速查表 ───────────────────────────────────────
print("── 速查表 ───────────────────────────────────")
examples = [
    ("arr[i, j, k]",        "标量（三轴整数）"),
    ("arr[i]",              "一块，shape (3,4)"),
    ("arr[i, j]",           "一行，shape (4,)"),
    ("arr[:, :2, :]",       "前2行，shape (2,2,4)"),
    ("arr[:, :, 1:3]",      "列1~2，shape (2,3,2)"),
    ("arr[:, 1:, :2]",      "后2行前2列，shape (2,2,2)"),
    ("arr[:, :, ::2]",      "偶数列，shape (2,3,2)"),
    ("arr[:, :, ::-1]",     "列反转，shape (2,3,4)"),
    ("arr[..., -1]",        "最后一列，shape (2,3)"),
    ("arr[np.newaxis]",     "升维，shape (1,2,3,4)"),
]
for code, desc in examples:
    print(f"  {code:<25} # {desc}")

3.花式索引

In [33]:
arr=np.array([10,20,30,40,50,60,70,80,90,100])
print(arr[[2,2,4,-1,0,-2]])

[ 30  30  50 100  10  90]


In [41]:
arr2 = np.array([
    [ 1,  2,  3,  4],
    [ 5,  6,  7,  8],
    [ 9, 10, 11, 12]
])
print(arr2[[0,0,2]],"\n")
#取出第0行第2行

print(arr2[:,[0,0,2]],"\n")
#取出所有行的第0列两次第2列一次

print(arr2[[0,2,1],[0,2,3]],"\n")
#一一配对

print(arr2[[0,2]][:,[1,3]])
#先取出行后在取列

#花式索引可以和切片索引混用


[[ 1  2  3  4]
 [ 1  2  3  4]
 [ 9 10 11 12]] 

[[ 1  1  3]
 [ 5  5  7]
 [ 9  9 11]] 

[ 1 11  8] 

[[ 2  4]
 [10 12]]


3.布尔索引

In [49]:
print(arr)
print(arr>25)
print(arr[arr>25])
print(arr[(arr>25)&(arr<75)])#每个条件都得加括号
#print(arr[arr>25 & arr<75])报错valueerror
print(arr[(arr<25)|(arr>85)])


[ 10  20  30  40  50  60  70  80  90 100]
[False False  True  True  True  True  True  True  True  True]
[ 30  40  50  60  70  80  90 100]
[30 40 50 60 70]
[ 10  20  80  90 100]


In [59]:
print(arr2,"\n")

print(arr2[arr2%2==0],"\n")
#arr[一维布尔数组]筛选行，arr[二维布尔数组]筛选元素
print(arr2[arr2[:,0:5]%3==0],"\n")
print(arr2[arr2[:,0]%3==0])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[ 2  4  6  8 10 12] 

[ 3  6  9 12] 

[[ 9 10 11 12]]


In [61]:
arr2[arr2%2==0]=0
print(arr2)

print(arr2[[True,False,True]])#mask==m

[[ 1  0  3  0]
 [ 5  0  7  0]
 [ 9  0 11  0]]
[[ 1  0  3  0]
 [ 9  0 11  0]]
