## 线性代数

In [1]:
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt
import math
from IPython.display import Image, display

In [2]:
u=np.array([5,1,3])
m1=np.array([4,5,1])
m2=np.array([5,1,5])
#计算夹角
def cosine_similarity(a,b):
    a = np.array(a)
    b = np.array(b)
    denominator = np.linalg.norm(a) * np.linalg.norm(b)
    if denominator==0:
        print("error")
    else:
        return np.dot(a,b)/denominator

print(cosine_similarity(u,m1))
print(cosine_similarity(u,m2))

0.7302967433402215
0.9704311900788593


In [3]:
print(np.cross(u, m1))  # [-14   7  21]
print(np.cross(m1, u))  # [ 14  -7 -21]

[-14   7  21]
[ 14  -7 -21]


A.T                 # 转置
A @ B               # 矩阵乘法
np.linalg.inv(A)    # 逆矩阵
np.linalg.det(A)    # 行列式
np.linalg.eig(A)    # 特征值/特征向量
np.linalg.svd(A)    # 奇异值分解
np.linalg.solve(A, b)  # 解线性方程组

In [4]:
m3 = np.array([[1., 2.], [3., 4.]])
m4 = np.linalg.inv(m3)
m4

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [7]:
print(np.round(m3@m4),"\n",np.round(m4@m3))

[[1. 0.]
 [0. 1.]] 
 [[1. 0.]
 [0. 1.]]


In [9]:
m5=np.array([[1,3,5],[2,4,6],[4,7,9]])
np.linalg.det(m5)

1.9999999999999993

In [10]:
np.linalg.matrix_rank(m5)

3

In [16]:
A=np.array([[1,2,1],[3,7,2],[2,2,1]])
b=np.array([8,23,9]).reshape(-1,1)
print(np.linalg.matrix_rank(A))
print(np.linalg.matrix_rank(np.hstack([A,b])))
print(np.linalg.solve(A,b))
print(np.linalg.inv(A)@b)

3
3
[[1.]
 [2.]
 [3.]]
[[1.]
 [2.]
 [3.]]


多项式

In [17]:
p1 = np.poly1d([3, 2, 1])
p2 = np.poly1d([1, 2, 3])
print(p1)
print(p2)

   2
3 x + 2 x + 1
   2
1 x + 2 x + 3


In [18]:
print(p1.coefficients)
print(p2.coeffs)

[3 2 1]
[1 2 3]


In [19]:
print(p1 + p2)
print(p1 * p2)

   2
4 x + 4 x + 4
   4     3      2
3 x + 8 x + 14 x + 8 x + 3


In [20]:
print(p1.deriv())
print(p1.integ())

 
6 x + 2
   3     2
1 x + 1 x + 1 x


In [21]:
p3 = np.poly1d([1, 3, 2])
print(p3.roots)

[-2. -1.]


In [22]:
from numpy.polynomial import Polynomial

p3 = Polynomial((2, 3, 1))
print(p3)           # 输出多项式
print(p3(3))        # 令x=3，计算多项式的值
print(p3.roots())   # 计算多项式的根
print(p3.degree())  # 获得多项式的次数
print(p3.deriv())   # 求导
print(p3.integ())   # 求不定积分

2.0 + 3.0 x + 1.0 x**2
20.0
[-2. -1.]
2
3.0 + 2.0 x
0.0 + 2.0 x + 1.5 x**2 + 0.33333333 x**3
